name: j1_theme
description: "A common theme class and Flutter builders for the J1 apps."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_mappable: ^4.2.2
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    path: ../j1_lints

  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
