name: j1_core

packages:
  - packages/**

scripts:
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test
      ignore:
        - '*web*'
        - '*example*'