import "package:flutter/widgets.dart";

// coverage:ignore-file
class JamIcons {
  JamIcons._();

  static const _kFontFam = "JamIcons";

  static const IconData unpinned = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData unorderedlist = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData video = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData strikethrough = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData stats = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData textcolor = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData underline = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData tasklist = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData text = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData tag = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData starfilled = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData paw = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData refresh = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData pinned = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData mic = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData pencil = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData language = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData paintbrush = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData italic = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData plug = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData help = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData orderedlist = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData infofilled = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData github = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData key = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData h2 = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData pizza = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData mountain = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData google = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData link = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData info = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData h1 = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData folder = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData folderfilled = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData eyedropper = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData close = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData eyeclosed = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData crown = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData homefilled = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData h3 = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData email = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData chevronleft = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData chevrondown = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData creditcard = IconData(0xe832, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData coin = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData bold = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData book = IconData(0xe837, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe838, fontFamily: _kFontFam);
  static const IconData chevronup = IconData(0xe839, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData brush = IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData chevronright = IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData bell = IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData basketball = IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData backgroundcolor = IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData apple = IconData(0xe840, fontFamily: _kFontFam);
  static const IconData animation = IconData(0xe841, fontFamily: _kFontFam);
  static const IconData alarmclock = IconData(0xe842, fontFamily: _kFontFam);
  static const IconData account = IconData(0xe843, fontFamily: _kFontFam);
}
