name: j1_router
description: A router for the J1 apps.
version: 1.0.3
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  equatable: ^2.0.5
  get_it: ^8.0.2
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.2
      
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
