name: j1_crash_handler
description: A crash handler for the J1 apps.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    path: ../j1_lints

  mocktail: ^1.0.4

flutter:
  uses-material-design: true
