name: j1_environment
description: "An environment for the J1 apps."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  j1_crash_handler:
    path: ../j1_crash_handler

  j1_logger:
    path: ../j1_logger

  j1_router:
    path: ../j1_router

  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    path: ../j1_lints

flutter:
  uses-material-design: true
