name: j1_lints
description: A set of lints for use throughout the J1 dart ecosystem.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  flutter_lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
