name: catalog
description: A test catalog for JW UI.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  j1_ui:
    path: ../../j1_ui

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  
  flutter_test:
    sdk: flutter

  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/dodgers.svg

  fonts:
    - family: JamIcons
      fonts:
        - asset: packages/j1_ui/fonts/JamIcons.ttf
