name: j1_core_base
description: The base components for the J1 Core library.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  dart_mappable: ^4.2.2
  logger: ^2.4.0
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  get_it: ^8.0.2
  go_router: ^15.1.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
