name: flutter tests

on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main, release]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install lcov
        run: sudo apt-get install lcov

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: check version
        run: flutter --version

      - name: update dependencies
        run: flutter pub get

      - name: update catalog dependencies
        working-directory: ./catalog
        run: flutter pub get

      - name: analyze
        run: flutter analyze

      - name: test
        run: bash ./run_coverage.sh

      - name: upload to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}