name: j1_ui
description: A set of common UI components for use throughout the J1 ecosystem.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    path: ../j1_lints
      
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/j1_logo.svg
